In [1]:
import os
import pickle
import cv2
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder

In [2]:
print("Bắt đầu định dạng lại ảnh")

Bắt đầu định dạng lại ảnh


In [3]:
df = pd.DataFrame(columns=['path', 'label'])
classnames = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18",
              "19", "20", "21", "22", "23", "24", "25", "26", "27",
              "28", "29", "30"]

In [4]:
for name in classnames:
    img_path = "dataChar/" + str(name) + "/"
    filelist = os.listdir(img_path)
    for file in filelist:
        if file != 'Thumbs.db':
            img = os.path.join(img_path, file)
            new_row = {'path': img, 'label': name}
            new_row_df = pd.DataFrame([new_row])
            df = pd.concat([df, new_row_df], ignore_index=True)
print(df)

                                path label
0      dataChar/0/motorcycle1006.jpg     0
1      dataChar/0/motorcycle1024.jpg     0
2      dataChar/0/motorcycle1030.jpg     0
3      dataChar/0/motorcycle1036.jpg     0
4      dataChar/0/motorcycle1042.jpg     0
...                              ...   ...
8655  dataChar/30/motorcycle7064.jpg    30
8656  dataChar/30/motorcycle7571.jpg    30
8657  dataChar/30/motorcycle7938.jpg    30
8658  dataChar/30/motorcycle8430.jpg    30
8659  dataChar/30/motorcycle9196.jpg    30

[8660 rows x 2 columns]


In [5]:
df.to_csv(r'dataBeforeTraining/pathImage28.csv', index=False)

In [6]:
list_data = []
data = pd.read_csv('dataBeforeTraining/pathImage28.csv')
X = data['path'].tolist()
Y = data['label'].tolist()

In [7]:
for i in X:
    print(i)
    img = cv2.imread(i)
    image = cv2.resize(img, (28, 28))
    list_data.append(image)

dataChar/0/motorcycle1006.jpg
dataChar/0/motorcycle1024.jpg
dataChar/0/motorcycle1030.jpg
dataChar/0/motorcycle1036.jpg
dataChar/0/motorcycle1042.jpg
dataChar/0/motorcycle1069.jpg
dataChar/0/motorcycle1078.jpg
dataChar/0/motorcycle109.jpg
dataChar/0/motorcycle1096.jpg
dataChar/0/motorcycle110.jpg
dataChar/0/motorcycle1106.jpg
dataChar/0/motorcycle112.jpg
dataChar/0/motorcycle1167.jpg
dataChar/0/motorcycle1188.jpg
dataChar/0/motorcycle1235.jpg
dataChar/0/motorcycle1246.jpg
dataChar/0/motorcycle125.jpg
dataChar/0/motorcycle1274.jpg
dataChar/0/motorcycle1343.jpg
dataChar/0/motorcycle1352.jpg
dataChar/0/motorcycle136.jpg
dataChar/0/motorcycle1375.jpg
dataChar/0/motorcycle1408.jpg
dataChar/0/motorcycle143.jpg
dataChar/0/motorcycle147.jpg
dataChar/0/motorcycle1471.jpg
dataChar/0/motorcycle1473.jpg
dataChar/0/motorcycle1485.jpg
dataChar/0/motorcycle1486 - Copy.jpg
dataChar/0/motorcycle1486.jpg
dataChar/0/motorcycle1550 - Copy.jpg
dataChar/0/motorcycle1550.jpg
dataChar/0/motorcycle1564.jpg
dat

In [8]:
list_data = np.array(list_data)
list_data

array([[[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [253, 253, 253],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [253, 253, 253],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [255, 255, 255],
         [255, 255, 255]],

        [[254, 254, 254],
         [  2,   2,   2],
         [  0,   0,   0],
         ...,
         [  5,   5,   5],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [254, 254, 254],
         ...,
         [  0,   0,   0],
         [205, 205, 205],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [254, 254, 254],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [253, 253, 253],
        

In [9]:
# bien doi nhan
le = preprocessing.LabelEncoder()
le.fit(Y)
label = le.transform(Y)
onehot_encoder = OneHotEncoder(sparse_output=False)
label = label.reshape(len(label), 1)
onehot_encoded = np.array(onehot_encoder.fit_transform(label))

print(onehot_encoded)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [10]:
# luu lai

pickle.dump(le, open('dataBeforeTraining/decode_label_28.pkl', 'wb'))
pickle.dump(onehot_encoded, open("dataBeforeTraining/one_hot_label_28.pkl", "wb"))
pickle.dump(list_data, open('dataBeforeTraining/data_28.pkl', 'wb'))

print('done')

done
